documentation:
  - .all-contributorsrc
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - PULL_REQUEST_TEMPLATE.md
  - README.md

test:
  - apps/**/*.spec.ts
  - apps/**/*.spec.js
