name: Stale
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  Stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            [~waiting]: https://img.shields.io/badge/-waiting-f5cd79.svg
            [~wontfix]: https://img.shields.io/badge/-wontfix-e77f67.svg
            [~dependency-fix]: https://img.shields.io/badge/-dependency%20fix-c44569.svg
            [~opened-pull-request]: https://img.shields.io/badge/-opened%20pull%20request-f5cd79.svg
            [~help-wanted]: https://img.shields.io/badge/-help%20wanted-63cdda.svg

            :warning: **Warning!** :warning:

            This issue was marked as stale due to a lack of activity for two months. :worried:
            In one month this issue will be closed if there is no more activity during this period. :grimacing:

            If you want to avoid this stale state you could add one of these labels:
            - [![label: waiting][~waiting]](https://github.com/Sonia-corporation/yokai/labels/waiting)
            - [![label: wontfix][~wontfix]](https://github.com/Sonia-corporation/yokai/labels/wontfix)
            - [![label: dependency-fix][~dependency-fix]](https://github.com/Sonia-corporation/yokai/labels/dependency-fix)
            - [![label: opened-pull-request][~opened-pull-request]](https://github.com/Sonia-corporation/yokai/labels/opened-pull-request)
            - [![label: help wanted][~help-wanted]](https://github.com/Sonia-corporation/yokai/labels/help%20wanted)
          stale-pr-message: |
            [~waiting]: https://img.shields.io/badge/-waiting-f5cd79.svg
            [~wontfix]: https://img.shields.io/badge/-wontfix-e77f67.svg
            [~dependency-fix]: https://img.shields.io/badge/-dependency%20fix-c44569.svg
            [~opened-pull-request]: https://img.shields.io/badge/-opened%20pull%20request-f5cd79.svg
            [~help-wanted]: https://img.shields.io/badge/-help%20wanted-63cdda.svg

            :warning: **Warning!** :warning:

            This pull request was marked as stale due to a lack of activity for two months. :worried:
            In one month this pull request will be closed if there is no more activity during this period. :grimacing:

            If you want to avoid this stale state you could add one of these labels:
            - [![label: waiting][~waiting]](https://github.com/Sonia-corporation/yokai/labels/waiting)
            - [![label: wontfix][~wontfix]](https://github.com/Sonia-corporation/yokai/labels/wontfix)
            - [![label: dependency-fix][~dependency-fix]](https://github.com/Sonia-corporation/yokai/labels/dependency-fix)
            - [![label: opened-pull-request][~opened-pull-request]](https://github.com/Sonia-corporation/yokai/labels/opened-pull-request)
            - [![label: help wanted][~help-wanted]](https://github.com/Sonia-corporation/yokai/labels/help%20wanted)
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'waiting,wontfix,dependency-fix,opened-pull-request,help%20wanted'
          stale-pr-label: 'no-pull-request-activity'
          exempt-pr-labels: 'waiting,wontfix,dependency-fix,opened-pull-request,help%20wanted'
          days-before-stale: 60
          days-before-close: 30
